export const TYPES = {
  Database: Symbol.for('Database'),
  DatabaseConnection: Symbol.for('DatabaseConnection'),
  GlobalErrorFilter: Symbol.for('GlobalErrorFilter'),
  //Countries
  CountryRepository: Symbol.for('CountryRepository'),
  CreateCountryUseCase: Symbol.for('CreateCountryUseCase'),
  FindAllCountriesUseCase: Symbol.for('FindAllCountriesUseCase'),
  FindByFiltersCountryUseCase: Symbol.for('FindByFiltersCountryUseCase'),
  FindByIdCountryUseCase: Symbol.for('FindByIdCountryUseCase'),
  FindByIsoCodeCountryUseCase: Symbol.for('FindByIsoCodeCountryUseCase'),
  UpdateCountryUseCase: Symbol.for('UpdateCountryUseCase'),
  RemoveCountryUseCase: Symbol.for('RemoveCountryUseCase'),
  //Languages
  LanguageRepository: Symbol.for('LanguageRepository'),
  CreateLanguageUseCase: Symbol.for('CreateLanguageUseCase'),
  FindAllLanguagesUseCase: Symbol.for('FindAllLanguagesUseCase'),
  FindByFiltersLanguageUseCase: Symbol.for('FindByFiltersLanguageUseCase'),
  FindByIdLanguageUseCase: Symbol.for('FindByIdLanguageUseCase'),
  FindByIsoCodeLanguageUseCase: Symbol.for('FindByIsoCodeLanguageUseCase'),
  UpdateLanguageUseCase: Symbol.for('UpdateLanguageUseCase'),
  RemoveLanguageUseCase: Symbol.for('RemoveLanguageUseCase'),
  //Publishers
  PublisherRepository: Symbol.for('PublisherRepository'),
  CreatePublisherUseCase: Symbol.for('CreatePublisherUseCase'),
  FindAllPublishersUseCase: Symbol.for('FindAllPublishersUseCase'),
  FindByFiltersPublisherUseCase: Symbol.for('FindByFiltersPublisherUseCase'),
  FindByIdPublisherUseCase: Symbol.for('FindByIdPublisherUseCase'),
  UpdatePublisherUseCase: Symbol.for('UpdatePublisherUseCase'),
  RemovePublisherUseCase: Symbol.for('RemovePublisherUseCase'),
  //Authors
  AuthorRepository: Symbol.for('AuthorRepository'),
  CreateAuthorUseCase: Symbol.for('CreateAuthorUseCase'),
  FindAllAuthorsUseCase: Symbol.for('FindAllAuthorsUseCase'),
  FindByFiltersAuthorUseCase: Symbol.for('FindByFiltersAuthorUseCase'),
  FindByIdAuthorUseCase: Symbol.for('FindByIdAuthorUseCase'),
  UpdateAuthorUseCase: Symbol.for('UpdateAuthorUseCase'),
  RemoveAuthorUseCase: Symbol.for('RemoveAuthorUseCase'),
  //Users
  UserRepository: Symbol.for('UserRepository'),
  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  LoginUserUseCase: Symbol.for('LoginUserUseCase'),
  FindByIdUserUseCase: Symbol.for('FindByIdUserUseCase'),
  FindAllUsersUseCase: Symbol.for('FindAllUsersUseCase'),
  FindByFiltersUserUseCase: Symbol.for('FindByFiltersUserUseCase'),
  UpdateProfileUseCase: Symbol.for('UpdateProfileUseCase'),
  RemoveUserUseCase: Symbol.for('RemoveUserUseCase'),
  //Security
  PasswordHasher: Symbol.for('PasswordHasher'),
  TokenProvider: Symbol.for('TokenProvider'),
  AuthGuard: Symbol.for('AuthGuard'),
  //Reading Lists
  ReadingListRepository: Symbol.for('ReadingListRepository'),
  ListItemRepository: Symbol.for('ListItemRepository'),
  CreateReadingListUseCase: Symbol.for('CreateReadingListUseCase'),
  FindByIdReadingListUseCase: Symbol.for('FindByIdReadingListUseCase'),
  FindByUserIdReadingListUseCase: Symbol.for('FindByUserIdReadingListUseCase'),
  FindPublicReadingListsUseCase: Symbol.for('FindPublicReadingListsUseCase'),
  FindByFiltersReadingListUseCase: Symbol.for('FindByFiltersReadingListUseCase'),
  UpdateReadingListUseCase: Symbol.for('UpdateReadingListUseCase'),
  RemoveReadingListUseCase: Symbol.for('RemoveReadingListUseCase'),
  AddBookToListUseCase: Symbol.for('AddBookToListUseCase'),
  RemoveBookFromListUseCase: Symbol.for('RemoveBookFromListUseCase'),
  GetListItemsUseCase: Symbol.for('GetListItemsUseCase'),
  UpdateListItemUseCase: Symbol.for('UpdateListItemUseCase'),
  //Reading Progress
  ReadingProgressRepository: Symbol.for('ReadingProgressRepository'),
  StartReadingUseCase: Symbol.for('StartReadingUseCase'),
  FindByIdProgressUseCase: Symbol.for('FindByIdProgressUseCase'),
  FindByUserAndBookProgressUseCase: Symbol.for('FindByUserAndBookProgressUseCase'),
  FindByUserIdProgressUseCase: Symbol.for('FindByUserIdProgressUseCase'),
  FindByFiltersProgressUseCase: Symbol.for('FindByFiltersProgressUseCase'),
  UpdateProgressUseCase: Symbol.for('UpdateProgressUseCase'),
  RemoveProgressUseCase: Symbol.for('RemoveProgressUseCase'),
  GetUserStatsUseCase: Symbol.for('GetUserStatsUseCase'),
  //Reviews
  ReviewRepository: Symbol.for('ReviewRepository'),
  CreateReviewUseCase: Symbol.for('CreateReviewUseCase'),
  FindByIdReviewUseCase: Symbol.for('FindByIdReviewUseCase'),
  FindByBookIdReviewUseCase: Symbol.for('FindByBookIdReviewUseCase'),
  FindRepliesByReviewIdUseCase: Symbol.for('FindRepliesByReviewIdUseCase'),
  FindByFiltersReviewUseCase: Symbol.for('FindByFiltersReviewUseCase'),
  UpdateReviewUseCase: Symbol.for('UpdateReviewUseCase'),
  RemoveReviewUseCase: Symbol.for('RemoveReviewUseCase'),
  GetBookRatingUseCase: Symbol.for('GetBookRatingUseCase'),
  //Recommendations
  RecommendationRepository: Symbol.for('RecommendationRepository'),
  GetCollaborativeRecommendationsUseCase: Symbol.for('GetCollaborativeRecommendationsUseCase'),
  GetPersonalRecommendationsUseCase: Symbol.for('GetPersonalRecommendationsUseCase'),
  GetPopularByCategoryUseCase: Symbol.for('GetPopularByCategoryUseCase'),
  GetTrendingUseCase: Symbol.for('GetTrendingUseCase'),
  GetSimilarBooksUseCase: Symbol.for('GetSimilarBooksUseCase'),
  //Books
  BookRepository: Symbol.for('BookRepository'),
  CreateBookUseCase: Symbol.for('CreateBookUseCase'),
  FindAllBooksUseCase: Symbol.for('FindAllBooksUseCase'),
  FindByFiltersBookUseCase: Symbol.for('FindByFiltersBookUseCase'),
  FindByIdBookUseCase: Symbol.for('FindByIdBookUseCase'),
  UpdateBookUseCase: Symbol.for('UpdateBookUseCase'),
  RemoveBookUseCase: Symbol.for('RemoveBookUseCase'),
  ToggleStatusBookUseCase: Symbol.for('ToggleStatusBookUseCase'),
};
